[package]
name = "bili-batch-unsubcribe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qr2term = "0.3.1"
inquire = "0.6.0"

anyhow = "1.0.69"

tracing = "0.1.37"
tracing-subscriber = "0.3"

serde_json = "1.0.94"

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "macros"]

[dependencies.reqwest]
version = "0.11.14"
features = ["cookies", "json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
